name: Build and Test

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build database
      run: docker-compose build

    - name: Create database
      run: docker compose up -d --build /devops/

    - name: Test
      run: mvn test

  build:

    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package
